### ISSUE TITLE
[BUG] "find" does not respect semver/expath-pkg spec

### ISSUE THREAD

**Issue by stexandev** [eXist-db/public-repo#72] opened 2021-07-08 07:03 UTC
**Describe the bug**
A package can describe a dependency on a processor with a semver range but this range is not interpreted correctly (imho). For example,

```xml
<dependency processor="http://exist-db.org" semver-min="4.6.1" semver-max="5"/>
```

is a valid semver range and should return the package when asked for versions above 4.6.1 and below 6.0.0 but instead, it only returns the package for versions above 4.6.1 and less than or equal to 5.0.0.

**Expected behavior**
Should return all versions less than 6.0.0.
This means, the app should interpret a semver declaration of "5" as a semver-template and not as "5.0.0".

**To Reproduce**
I could not find a package in the exist-public-repo that could reproduce this issue but we are running the 2.0 version of the app on exist-db 5.3.0 at https://ci.de.dariah.eu/exist-repo
The package odd-serializer uses the processor dependency declaration statet above and can be found [in our repository](https://ci.de.dariah.eu/exist-repo/packages/odd-serializer.html?eXist-db-min-version=4.6.1).

As expected, the package is returned for versions above 4.6.1, e.g.:
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=4.99.99

Also, it is returned for 5, 5.0, 5.0.0:
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5.0
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5.0.0

But, and this is the issue, it is not returned for any semver above 5.0.0, be it 5.1, 5.0.1, 5.1.0
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5.1
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5.0.1
https://ci.de.dariah.eu/exist-repo/find?abbrev=odd-serializer&processor=5.1.0

**Remarks**

Of course, this could also be an issue in semver.xq, which, as of now, i have not (yet) checked.

Also, I know that the [expath-pkg spec](http://expath.org/spec/pkg#procdep) states
> The meaning of the versionning attributes on processor dependencies is defined by each processor.

But since the documentation does not state this meaning, I would expect the app to behave the same way as it is [required by the spec for package dependencies](http://expath.org/spec/pkg#pkgdep).

**Comment by duncdrum** [comment] 2021-07-08 07:36
hmm TBH i m not convinced that adding support for semver templates as defined by the expath-pkg specs is a good approach. As you already stated, we are within the spec to define behaviour for our processor, and to require valid semver for these attributes. The issue is easily avoidable by 
```xml
<dependency processor="http://exist-db.org" semver-min="4.6.1" semver-max="6.0.0"/>
```

so my first instinct would be to issue a warning along the lines of `WARNING: SemVer templates are not supported, please provide a valid semVer when specifiying dependencies.`

Curious to hear what others think though.

**Comment by stexandev** [comment] 2021-07-08 07:42
I am sorry to tell you that your proposal is **not** a valid solution/workaround to this issue because your declaration would include version `6.0.0`. The only way to specify a semver range of "less than `6.0.0`" with `semver-max` is to support semver templates.

**Comment by duncdrum** [comment] 2021-07-08 09:24
sure `5.99.999` would do the trick, the point is that there are easily available workarounds.

**Comment by stexandev** [comment] 2021-07-08 09:52
I dont't want to be too pedantic here but no, this would not do the trick, since version `5.100.0` (and all above) is not covered by your propsed workaround. We could go on and discuss many more "workarounds" but this does not substantially add to the discussion of this issue. For me, it is a matter of specification. Since existdb does not state how `semver-max` is to be interpreted, I expect it to comply with the specification of [expath-pkg](http://expath.org/spec/pkg) which is described in the text of this issue.

**Comment by duncdrum** [comment] 2021-07-08 10:33
> Since existdb does not state how semver-max is to be interpreted, I expect it to comply with the specification of expath-pkg which is described in the text of this issue. 

well the question is if 
- what exist-db [states](https://github.com/eXist-db/documentation/blob/e6ca589af27370b61d52e449f2a3a3527f69b868/src/main/xar-resources/data/repo/repo.xml#L156) it implements is a sufficiently clear and might need to be modified, or
- if we need to adjust code to implement ranges

**Comment by joewiz** [comment] 2021-07-13 22:33
@stexandev As discussed on yesterday's Community Call, I agree that your report is a valid issue with the public-repo app. I was somehow never aware that that the EXPath Package spec defined "SemVer templates," so I completely neglected this aspect of the spec in my recent work on improving the public repo's support for SemVer 2.0. The good news is that in [our research](https://github.com/expath/expath-pkg-java/issues/11), eXist's core respects the EXPath Package spec's notion of "SemVer templates" (i.e., eXist 5.3.0 should happily install the package with a processor dependency on eXist expressed as `semver-max="5"`), and therefore, public-repo should as well. I am working on a fix to public-repo which will align public-repo's behavior with eXist's.

**Comment by joewiz** [comment] 2022-07-06 13:54
This semver issue is not fixed.

**Comment by joewiz** [comment] 2022-12-31 23:47
@stexandev Sorry it's taken me **so long** to follow through on my promise to fix this issue! I took a few swipes at it and finally have a solution. The PRs are https://github.com/eXist-db/semver.xq/pull/18 and https://github.com/eXist-db/public-repo/pull/79. Once they're merged both projects will need new releases. Hopefully we'll have it for you before too long. In the meantime, Happy New Year!

**Closed** 2023-01-07 04:34 UTC
Labels: bug

**Comment by joewiz** [comment] 2023-01-07 05:05
@stexandev The fix was released in version 2.2.0:

- https://github.com/eXist-db/public-repo/releases/tag/v2.2.0
- https://exist-db.org/exist/apps/public-repo/packages/public-repo?eXist-db-min-version=5.3.0

If you upgrade https://ci.de.dariah.eu/exist-repo, please let us know if everything works as expected or not.

**Comment by stexandev** [comment] 2023-01-07 14:23
thank you; i am going to test this asap!

**Comment by stexandev** [comment] 2023-01-20 08:13
I finally managed to test the current behaviour of the public-repo against the semver-specs and as far as I can tell, it works as expected! Thanks a lot. And of course, if I come across any further issues, be sure I will open another issue :smiley: 
Happy New Year from Göttingen.

**Comment by joewiz** [comment] 2023-01-20 12:59
@stexandev Excellent! Sounds good. ;)
